### ISSUE TITLE
Teachers & Classrooms

### ISSUE THREAD

**Issue by TheWABBIT1** [tiquionophist/hhs-scheduler#12]
What I have found to be an issue. Is that if a teacher is teaching a single subject. hhs-scheduler will have the teacher teaching that subject in random classrooms through out the day. And it does not matter if the teacher is only teaching that subject once that day for one class, or if they are teaching that class multiple times in the same day for the same class. The teacher is always teaching the in a different classroom.

For example:
Teacher:                            Subject:
April Raymund                  Geography
Beth Manili                       Math
Jessica Underwood           History
Nina Parker                       English

And there is 4 Classes, referred to as Class 1-A, Class 1-B, Class 1-C, Class 1-D

Now, if I use hhs-scheduler to create a class schedule. Geography will be taught in classroom 1, Math is in classroom 4, History in classroom 5, and English in classroom 7. But, the next day the subjects are scheduled in different classrooms. The classrooms that are in will be different. Geography is now in classroom 3, Math is now in classroom 6, History is now in classroom 4, and English is now in classroom 2.

And that is just for Class 1-A and if you only have all class subjects being scheduled once a day. If any of the class subjects are scheduled more than once a day. The next time it is scheduled in that same day. It is in a different classroom.

Then you have to deal with Class 1-B, Class 1-C and Class 1-D. Even though the same subjects are being taught by the same Teachers to the other classes. They are being taught in a different classroom each time the subject is scheduled.

Personally, I don't know enough about Eastern Countries school systems to say anything about them. But, I have know enough about the schools in the US, Germany and the UK (both public and private) to say that for most of the public schools, and damn near all the private schools, that are the US High School equivalent and/or higher. The teachers do not constantly change classrooms. It is the students that constantly change classrooms between subjects.

The Teachers are assigned a classroom and that is where they will teach all of their subjects in. The only exception to this, is that if a Teacher teaching multiple subjects. And the school has a specific classroom assigned for specific subjects. Then the Teacher will teach that specific subject in the classroom that the school has assigned for it. And then the rest of the subjects, if they do not have a specific classroom assigned for the subject, will be taught in the classroom assigned to the teacher.

So, it would be very nice if hhs-scheduler was to assign subjects to specific classrooms. And to schedule the classes using those specific classrooms.

I know that this would only work if you are only hiring One Teacher per subject.

**Comment by tiquionophist** [comment]
This is a good idea, and not too hard to do. In general, I think there are probably two strategies:
- Have the same class always in the same classroom with teachers switching out for each subject. Probably not as common IRL but not unheard of either, and might be easier to track down a specific class/student in the game.
- Have the same teacher always in the same classroom with classes switching out for each subject, as you suggested. More realistic and I think it is still viable even with a teacher teaching multiple subjects - they still only teach once per period so they can switch subjects but stay in the same classroom (as long as it doesn't require a special classroom). Basically, the scheduler would assign a classroom to each teacher and just use that classroom for them each time.

There might be more ways to do it, but I'll plan to implement these two, hopefully in the next release.
