### ISSUE TITLE
Alternative link to game download

### ISSUE THREAD

**Issue by strange-creature** [tiquionophist/hhs-scheduler#13]
Since the game development site is down it may be worth to add alternative links for game download:

Game topic on F95:
https://f95zone.to/threads/hentai-high-school-v1-10-0-public-beta-sp1-sp4-hhs.1016/

Temporary Discord server:
https://discord.gg/u8rsGaNgHA

**Comment by strange-creature** [comment]
New forum address:
https://henthighschool.net/

**Comment by tiquionophist** [comment]
Thanks. Closing the issue now to keep the tracker clean.

**Comment by strange-creature** [comment]
`README.md` still points to old address: https://www.henthighschool.com/hhsplus/

**Comment by tiquionophist** [comment]
Fixed, thanks
