### ISSUE TITLE
Classroom conflicts (base game)

### ISSUE THREAD

**Issue by DeniedInMT** [tiquionophist/hhs-scheduler#3]
When attempting to use your scheduler with Physics and Chemistry classes enabled, in the base game (no mods), Physics attempts to use a Physics classroom, when it is located in the Chemistry classroom instead.

Otherwise a very useful and helpful tool!

**Comment by tiquionophist** [comment]
Thanks for the report! I don't know where the "Physics" classroom comes from, for some reason I thought one existed. This will be fixed in the next release.
