### ISSUE TITLE
Error when importing save with 'Anatomy Class'

### ISSUE THREAD

**Issue by dashpace778** [tiquionophist/hhs-scheduler#6]
![image](https://user-images.githubusercontent.com/5000290/141670572-9525ccc4-7fb4-4588-8b65-12090534ddf2.png)

**Comment by dashpace778** [comment]
Running HHS+ with SP7 and any attempt to import a save with the anatomy class leads to the above error message, and exporting a save with the anatomy class enabled and attempting to use the 'Manage School' button leads to the following error in HHS+:

![image](https://user-images.githubusercontent.com/5000290/141670679-57674793-f2d7-4784-92e8-337a8b2f7e60.png)

A small bit of file searching leads me to believe the scheduler program refers to this class as 'Anatomy', while the game refers to it as 'Anatomy Class'

**Comment by tiquionophist** [comment]
Thanks for the detailed report! This will be fixed in the next release.
